# Generated by Django 4.2 on 2023-04-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
