# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_pb2 as grpc__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageEchoStub(object):
    """Methods
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServerEcho = channel.unary_unary(
                '/MessageEcho/ServerEcho',
                request_serializer=grpc__pb2.ClientResponse.SerializeToString,
                response_deserializer=grpc__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.ServerEchoStream = channel.unary_stream(
                '/MessageEcho/ServerEchoStream',
                request_serializer=grpc__pb2.ClientResponse.SerializeToString,
                response_deserializer=grpc__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.ServerEchoFromClientStream = channel.stream_unary(
                '/MessageEcho/ServerEchoFromClientStream',
                request_serializer=grpc__pb2.ClientResponse.SerializeToString,
                response_deserializer=grpc__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.ServerEchoStreamFromStreamClientStream = channel.stream_stream(
                '/MessageEcho/ServerEchoStreamFromStreamClientStream',
                request_serializer=grpc__pb2.ClientResponse.SerializeToString,
                response_deserializer=grpc__pb2.ServerResponse.FromString,
                _registered_method=True)


class MessageEchoServicer(object):
    """Methods
    """

    def ServerEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerEchoStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerEchoFromClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerEchoStreamFromStreamClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageEchoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServerEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerEcho,
                    request_deserializer=grpc__pb2.ClientResponse.FromString,
                    response_serializer=grpc__pb2.ServerResponse.SerializeToString,
            ),
            'ServerEchoStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerEchoStream,
                    request_deserializer=grpc__pb2.ClientResponse.FromString,
                    response_serializer=grpc__pb2.ServerResponse.SerializeToString,
            ),
            'ServerEchoFromClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ServerEchoFromClientStream,
                    request_deserializer=grpc__pb2.ClientResponse.FromString,
                    response_serializer=grpc__pb2.ServerResponse.SerializeToString,
            ),
            'ServerEchoStreamFromStreamClientStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ServerEchoStreamFromStreamClientStream,
                    request_deserializer=grpc__pb2.ClientResponse.FromString,
                    response_serializer=grpc__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MessageEcho', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MessageEcho', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageEcho(object):
    """Methods
    """

    @staticmethod
    def ServerEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MessageEcho/ServerEcho',
            grpc__pb2.ClientResponse.SerializeToString,
            grpc__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerEchoStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/MessageEcho/ServerEchoStream',
            grpc__pb2.ClientResponse.SerializeToString,
            grpc__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerEchoFromClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/MessageEcho/ServerEchoFromClientStream',
            grpc__pb2.ClientResponse.SerializeToString,
            grpc__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerEchoStreamFromStreamClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/MessageEcho/ServerEchoStreamFromStreamClientStream',
            grpc__pb2.ClientResponse.SerializeToString,
            grpc__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
